version: '2'

services:
  app:
    build: ./app
    command: --rinkeby --rpcapi "db,personal,eth,net,web3" --rpccorsdomain='*' --rpc --rpcaddr="0.0.0.0"
    volumes:
      - $HOME/.rinkeby:/root
      - ./app:/app
      - ../elchapo:/elchapo
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"

# https://docs.docker.com/compose/networking/#configuring-the-default-network, "Using a pre-existing network"
networks:
  default:
    external:
      name: bigapirb_default
